from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='dashboard-index'),
    path('scan/new/', views.scan_new, name='dashboard-scan-new'),
    path('scan/<uuid:scan_id>/', views.scan_detail, name='dashboard-scan-detail'),
    path('scan/<uuid:scan_id>/delete/', views.scan_delete, name='dashboard-scan-delete'),
    path('scan/<uuid:scan_id>/stop/', views.scan_stop, name='dashboard-scan-stop'),
    path('scan/<uuid:scan_id>/status/', views.scan_status_api, name='dashboard-scan-status'),
    path('trends/', views.trends, name='dashboard-trends'),
    path('trends/<uuid:pk>/delete/', views.trend_delete, name='dashboard-trend-delete'),
    path('settings/', views.settings_page, name='dashboard-settings'),
    path('organization/', views.organization_list, name='dashboard-organization'),
    path('organization/new/', views.organization_new, name='dashboard-organization-new'),
    path('organization/<int:pk>/edit/', views.organization_edit, name='dashboard-organization-edit'),
    path('organization/<int:pk>/delete/', views.organization_delete, name='dashboard-organization-delete'),
    path('organization/<int:pk>/set-default/', views.organization_set_default, name='dashboard-organization-set-default'),
    path('api/stats/', views.api_stats, name='dashboard-api-stats'),
    path('api/wazuh-agents/', views.api_wazuh_agents, name='dashboard-api-wazuh-agents'),
    path('api/openvas-tasks/', views.api_openvas_tasks, name='dashboard-api-openvas-tasks'),
    path('api/cwe-cves/', views.api_cwe_cves, name='dashboard-api-cwe-cves'),
    path('scan/<uuid:scan_id>/ai-analyze/', views.scan_ai_analyze, name='dashboard-scan-ai-analyze'),
    path('scan/<uuid:scan_id>/exploit-check/', views.scan_exploit_check, name='dashboard-scan-exploit-check'),
    path('report/', views.report_builder, name='dashboard-report-builder'),
    path('scans/bulk-delete/', views.scans_bulk_delete, name='dashboard-scans-bulk-delete'),
    path('agreements/', views.agreement_list, name='dashboard-agreement-list'),
    path('agreements/new/', views.agreement_new, name='dashboard-agreement-new'),
    path('agreements/<int:pk>/edit/', views.agreement_edit, name='dashboard-agreement-edit'),
    path('agreements/<int:pk>/delete/', views.agreement_delete, name='dashboard-agreement-delete'),
    path('certificates/', views.certificate_list, name='dashboard-certificate-list'),
    path('certificates/upload/', views.certificate_upload, name='dashboard-certificate-upload'),
    path('certificates/<int:pk>/delete/', views.certificate_delete, name='dashboard-certificate-delete'),
    path('agreements/template/upload/', views.upload_agreement_template, name='dashboard-agreement-template-upload'),
]
