# Generated by Django 6.0.2 on 2026-02-16 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('spider', 'Spider'), ('active', 'Active Scan'), ('ajax', 'Ajax Spider'), ('full', 'Full Scan')], default='full', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('zap_scan_id', models.CharField(blank=True, max_length=100)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_ref', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('risk', models.IntegerField(default=0, help_text='0=Info, 1=Low, 2=Medium, 3=High')),
                ('confidence', models.IntegerField(default=0, help_text='0=FP, 1=Low, 2=Medium, 3=High')),
                ('url', models.TextField(blank=True)),
                ('param', models.CharField(blank=True, max_length=500)),
                ('attack', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('cwe_id', models.IntegerField(default=0)),
                ('wasc_id', models.IntegerField(default=0)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('cvss_vector', models.CharField(blank=True, max_length=200)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scanner.scan')),
            ],
            options={
                'ordering': ['-risk', '-cvss_score'],
            },
        ),
        migrations.AddField(
            model_name='scan',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanner.scantarget'),
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_month', models.DateField(help_text='First day of month')),
                ('total_scans', models.IntegerField(default=0)),
                ('avg_risk_score', models.FloatField(default=0.0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='scanner.scantarget')),
            ],
            options={
                'ordering': ['-year_month'],
                'unique_together': {('target', 'year_month')},
            },
        ),
    ]
