# Generated by Django 6.0.2 on 2026-02-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='owasp_category',
            field=models.CharField(blank=True, help_text='OWASP 2025 category e.g. A01, A03', max_length=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='tool',
            field=models.CharField(default='zap', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='critical_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='critical_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='tool',
            field=models.CharField(choices=[('zap', 'OWASP ZAP'), ('trivy', 'Trivy'), ('sonarqube', 'SonarQube'), ('testssl', 'testssl.sh'), ('wazuh', 'Wazuh'), ('openvas', 'OpenVAS')], default='zap', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='risk',
            field=models.IntegerField(default=0, help_text='0=Info, 1=Low, 2=Medium, 3=High, 4=Critical'),
        ),
    ]
