# Generated by Django 6.0.2 on 2026-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alert_owasp_category_alert_tool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=300, verbose_name='ชื่อหน่วยงาน (ไทย)')),
                ('name_en', models.CharField(blank=True, default='', max_length=300, verbose_name='ชื่อหน่วยงาน (อังกฤษ)')),
                ('logo', models.ImageField(blank=True, upload_to='org/', verbose_name='โลโก้')),
                ('address', models.TextField(blank=True, default='', verbose_name='ที่อยู่')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='เบอร์โทร')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='อีเมล')),
                ('preparer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='ชื่อผู้จัดทำรายงาน')),
                ('preparer_title', models.CharField(blank=True, default='', max_length=200, verbose_name='ตำแหน่งผู้จัดทำ')),
                ('approver_name', models.CharField(blank=True, default='', max_length=200, verbose_name='ชื่อผู้บริหาร')),
                ('approver_title', models.CharField(blank=True, default='', max_length=200, verbose_name='ตำแหน่งผู้บริหาร')),
                ('document_number_prefix', models.CharField(blank=True, default='VA-RPT-', max_length=50, verbose_name='Prefix เลขที่เอกสาร')),
            ],
            options={
                'verbose_name': 'Organization Profile',
                'verbose_name_plural': 'Organization Profile',
            },
        ),
    ]
