# Generated by Django 6.0.2 on 2026-02-18 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_organizationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cwe_id', models.IntegerField(default=0)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('risk', models.IntegerField(default=0)),
                ('technical_explanation', models.TextField(blank=True)),
                ('business_impact', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='scanner.scan')),
            ],
            options={
                'ordering': ['-risk', '-cvss_score'],
                'unique_together': {('scan', 'name', 'cwe_id')},
            },
        ),
    ]
