# Generated by Django 6.0.2 on 2026-02-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_add_alert_ai_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='tool',
            field=models.CharField(choices=[('zap', 'OWASP ZAP'), ('trivy', 'Trivy'), ('sonarqube', 'SonarQube'), ('testssl', 'testssl.sh'), ('wazuh', 'Wazuh'), ('openvas', 'OpenVAS'), ('nuclei', 'Nuclei'), ('nmap', 'Nmap')], default='zap', max_length=20),
        ),
    ]
