# Generated by Django 6.0.2 on 2026-02-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_pentest_agreement_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pentestagreement',
            name='test_periods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='pentestagreement',
            name='test_hours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
