# Generated by Django 6.0.2 on 2026-02-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_add_test_periods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationprofile',
            options={'ordering': ['-is_default', 'name_th'], 'verbose_name': 'Organization Profile', 'verbose_name_plural': 'Organization Profiles'},
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='หน่วยงานหลัก'),
        ),
    ]
