# Generated by Django 6.0.2 on 2026-02-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0015_org_multi_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='pentestagreement',
            name='org_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='หน่วยงาน (สำหรับ PDF)'),
        ),
    ]
