# Generated by Django 6.0.2 on 2026-02-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0016_add_org_id_to_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='tool_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
