# Generated by Django 6.0.2 on 2026-02-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0017_add_tool_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200, verbose_name='ชื่อ-นามสกุล')),
                ('course_name', models.CharField(max_length=300, verbose_name='ชื่อหลักสูตร')),
                ('issuer', models.CharField(blank=True, max_length=300, verbose_name='หน่วยงานที่ให้')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='ไฟล์ใบประกาศ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['person_name', 'course_name'],
            },
        ),
    ]
